version: "{build}"

os: Visual Studio 2015

platform: 
  - Win32
  - x64

environment:
  MSVC_DEFAULT_OPTIONS: ON

branches:
  only:
    - transwarp1.X

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\transwarp

before_build:
  - cmd: cd C:\projects\transwarp
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_CXX_COMPILER_ARG1=/std:c++14 ..

build:
  project: C:\projects\transwarp\build\transwarp.sln
  parallel: true

test_script:
  - cmd: cd C:\projects\transwarp\build
  - cmd: ctest --verbose
